# -*- coding: utf-8 -*-
"""TASK 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-pQ_uuKhVSrD4uiZKxqD5yL3J1K0NAO5

***TASK 1: Iris Flowers Classification ML Project***

**Importing the libraries**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pb
import seaborn as sns
# %matplotlib inline

"""**Reading the dataset**"""

#made a list
columns=['Sepal Length','Sepal width','Petal Length','Petal Width','Class labels']
#reading the data
data1=pb.read_csv('iris.data',names=columns)
#to look at the loaded data
data1.head(150)

"""**Visualizing and analyzing the data**"""

#to visualize and analyze the data
data1.describe()
sns.pairplot(data1,hue='Class labels')

"""**Separating the columns**"""

#separating input and output columns
data=data1.values
v1=data[:,0:4]
v2=data[:,4]

"""**Splitting data testing and training**"""

#splitting data testing and training
from sklearn.model_selection import train_test_split 
xtrain, xtest, y_train, ytest= train_test_split(v1,v2, test_size=0.4)

"""**Support vector machine algorithm**"""

from sklearn.svm import SVC 
model_svc= SVC()
model_svc.fit(xtrain,y_train)
p1=model_svc.predict(xtest)
from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,p1)*100)

"""**Logistic Regression**"""

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(xtrain,y_train)

from sklearn.metrics import accuracy_score
predict2=lr.predict(xtest)
print(accuracy_score(ytest,predict2)*100)

"""**Decision tree classifier**"""

from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(xtrain,y_train)
predict3=dtc.predict(xtest)
from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,predict3)*100)

"""**Classification Report**"""

from sklearn.metrics import classification_report
print(classification_report(ytest,predict3))